//
//  DetailScreenInteractor.swift
//  Marvel-App
//
//  Created by Carles Grau Galvan on 12/05/2018.
//  Copyright (c) 2018 Carles Grau Galvan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailScreenBusinessLogic
{
    var selectedCharacter: Character! {get set}
    func presentCharacter(response: DetailScreen.SelectedCharacter.Response)
}

protocol DetailScreenDataStore
{
  var selectedCharacter: Character! {get set}
}

class DetailScreenInteractor: DetailScreenBusinessLogic, DetailScreenDataStore
{
  var presenter: DetailScreenPresentationLogic?
  var worker: DetailScreenWorker?
  var selectedCharacter: Character!
  
  // MARK: Do something
  
  func presentCharacter(response: DetailScreen.SelectedCharacter.Response)
  {
    let response = DetailScreen.SelectedCharacter.Response()
    presenter?.presentCharacter(response: response)
  }
}
