//
//  DetailScreenWorker.swift
//  Marvel-App
//
//  Created by Carles Grau Galvan on 12/05/2018.
//  Copyright (c) 2018 Carles Grau Galvan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailScreenWorker {
    /// Get **Response** containing **Delegate** and **DataSource** configured with an array of **Item**
    ///
    /// - Parameters:
    ///     - items: Array of *Items* to add them to dataSource.
    /// - Returns:
    ///     Response(dataSource:*ResourceCollectionDataSource*, delegate:*ResourceCollectionDelegate*)
    func getCollectionSetupResponse(items: [Item]?) -> DetailScreen.CollectionSettings.Response {
        let dataSource = ResourceCollectionDataSource()
        dataSource.resourceData = items?.filter {!$0.resourceURI.contains("image_not_available")}
        let delegate = ResourceCollectionDelegate()
        return DetailScreen.CollectionSettings.Response(dataSource: dataSource, delegate: delegate)
    }
}
