//
//  DetailScreenPresenter.swift
//  Marvel-App
//
//  Created by Carles Grau Galvan on 12/05/2018.
//  Copyright (c) 2018 Carles Grau Galvan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailScreenPresentationLogic
{
  func presentCharacter(response: DetailScreen.SelectedCharacter.Response)
}

class DetailScreenPresenter: DetailScreenPresentationLogic
{
  weak var viewController: DetailScreenDisplayLogic?
  
  // MARK: Do something
  
    func presentCharacter(response: DetailScreen.SelectedCharacter.Response)
    {
        let response = DetailScreen.SelectedCharacter.ViewModel()
        viewController?.displayCharacter(viewModel: response)
    }
}
