//
//  MainScreenWorkerTests.swift
//  Marvel-App
//
//  Created by Carles Grau Galvan on 13/05/2018.
//  Copyright (c) 2018 Carles Grau Galvan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Marvel_App
import XCTest

class MainScreenWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: MainScreenWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupMainScreenWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupMainScreenWorker() {
        sut = MainScreenWorker()
    }

    // MARK: Test doubles

    // MARK: Tests
    func testSearch() {
        // Given
        let exp = expectation(description: "Parsing ComicThumbnail")

        // When
        sut.search(string: "Venom") { (_, error) in
            if error == nil {
                exp.fulfill()
            } else {
                XCTFail("error is not nil.")
            }
        }

        // Then
        waitForExpectations(timeout: 1.0) { (_) -> Void in
            print("response")
        }
    }

    func testGetComicThumbnail() {
        // Given
        let exp = expectation(description: "Parsing ComicThumbnail")
        let venom = Mock.CharacterMock().venom

        // When
        sut.getComicThumbnailData(url: venom.resourceURI) { (_, error) in
            if error == nil {
                exp.fulfill()
            } else {
                XCTFail("error is not nil.")
            }
        }

        // Then
        waitForExpectations(timeout: 1.0) { (_) -> Void in
            print("response")
        }
    }
}
