//
//  DetailScreenWorkerTests.swift
//  Marvel-App
//
//  Created by Carles Grau Galvan on 13/05/2018.
//  Copyright (c) 2018 Carles Grau Galvan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Marvel_App
import XCTest

class DetailScreenWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: DetailScreenWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupDetailScreenWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupDetailScreenWorker()
  {
    sut = DetailScreenWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testGetCollectionData()
  {
    // Given
    let items = Mock.ResourceMock().res.items
    
    // When
    let data = sut.getCollectionSetupResponse(items: items)
    
    // Then
    XCTAssertNotNil(data)
    XCTAssertNotNil(data.dataSource)
    XCTAssertNotNil(data.delegate)
    XCTAssertNotNil(data.dataSource.resourceData)
  }
}
