//
//  MainScreenInteractorTests.swift
//  Marvel-App
//
//  Created by Carles Grau Galvan on 13/05/2018.
//  Copyright (c) 2018 Carles Grau Galvan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Marvel_App
import XCTest

class MainScreenInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MainScreenInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMainScreenInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMainScreenInteractor()
  {
    sut = MainScreenInteractor()
  }
  
  // MARK: Test doubles
  
  class MainScreenPresentationLogicSpy: MainScreenPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: MainScreen.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = MainScreenPresentationLogicSpy()
    sut.presenter = spy
    let request = MainScreen.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
